# Generated by Django 2.1.7 on 2019-02-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='hindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Place_of_study', models.TextField()),
                ('Prin_invest', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Desig', models.CharField(max_length=250)),
                ('NAme_of_research_fellow', models.CharField(max_length=250)),
                ('Invitation_paragraph', models.TextField()),
                ('Intro', models.TextField()),
                ('Why_am_i', models.TextField()),
                ('Duration', models.TextField()),
                ('How_many', models.TextField()),
                ('IS_my_part', models.TextField()),
                ('Can_i_withdraw', models.TextField()),
                ('What_will_be_done', models.TextField()),
                ('What_are_my_responsibility', models.TextField()),
                ('What_are_risk', models.TextField()),
                ('Confidentiality', models.TextField()),
                ('Whom_contact', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.hindu'),
        ),
    ]
